import {MD3LightTheme, MD3DarkTheme} from 'react-native-paper';
import useAppContext from './hooks/useAppContext';
import {
  BGC_CRITICAL_COLOR,
  BGC_INFO_COLOR,
  BGC_SUCCESS_COLOR,
  BGC_TOAST_CRITICAL,
  BGC_TOAST_INFO,
  BGC_TOAST_SUCCESS,
  BGC_TOAST_WARNING,
  BGC_WARNING_COLOR,
  BLACK_COLOR,
  BLACK_COLOR_DARK,
  BORDER_COLOR,
  BORDER_COLOR_DARK,
  CRITICAL_COLOR,
  DISABLED_COLOR,
  INFO_COLOR,
  MAIN_COLOR,
  MAIN_COLOR_DARK,
  MAIN_TEXT_COLOR,
  PRIMARY_COLOR,
  PRIMARY_COLOR_DARK,
  SUCCESS_COLOR,
  TOAST_CRITICAL,
  TOAST_INFO,
  TOAST_SUCCESS,
  TOAST_WARNING,
  WARNING_COLOR,
  WHITE_COLOR,
  WHITE_COLOR_DARK,
  WHITE_COLOR_GRAY_100,
  WHITE_COLOR_GRAY_100_DARK,
} from '../styles/colors.global';

export const useGetColorThemeDisplay = () => {
  const {state} = useAppContext();
  const {appearance_display} = state.set_data;

  const themeDark = {
    colors: {
      ...MD3DarkTheme.colors,
      WHITE_COLOR: WHITE_COLOR_DARK,
      WHITE_COLOR_GRAY_100: WHITE_COLOR_GRAY_100_DARK,
      BLACK_COLOR: BLACK_COLOR_DARK,
      MAIN_COLOR: MAIN_COLOR_DARK,
      PRIMARY_COLOR: PRIMARY_COLOR_DARK,
      DATE_TEXT_COLOR: '#FFFFFF',
      DATE_TEXT_DISABLED_COLOR: '#2d4150',
      BORDER_COLOR: BORDER_COLOR_DARK,
      BACKGROUND_CARD: '#313131',
      BACKGROUND_CARD_TOAST: '#15182b',
      HIGHLIGHT_COLOR: '#f1c40f',
      DRAG_ITEM_BGC_COLOR: 'rgba(255, 255, 255, 0.2)',
      BORDER_KIT_COLOR: '#718093',
      BGC_CHILD_LOADING: 'rgba(0,0,0,0.6)',
      BGC_LOADING: 'rgba(0,0,0,0.4)',
      DISABLED_COLOR: DISABLED_COLOR,
      BORDER_INPUT_COLOR: 'rgba(255, 255, 255, 0.2)',
      INFO_COLOR: INFO_COLOR,
      BGC_INFO_COLOR: BGC_INFO_COLOR,
      SUCCESS_COLOR: SUCCESS_COLOR,
      BGC_SUCCESS_COLOR: BGC_SUCCESS_COLOR,
      WARNING_COLOR: WARNING_COLOR,
      BGC_WARNING_COLOR: BGC_WARNING_COLOR,
      CRITICAL_COLOR: CRITICAL_COLOR,
      BGC_CRITICAL_COLOR: BGC_CRITICAL_COLOR,
      TOAST_SUCCESS: TOAST_SUCCESS,
      BGC_TOAST_SUCCESS: BGC_TOAST_SUCCESS,
      TOAST_CRITICAL: TOAST_CRITICAL,
      BGC_TOAST_CRITICAL: BGC_TOAST_CRITICAL,
      TOAST_WARNING: TOAST_WARNING,
      BGC_TOAST_WARNING: BGC_TOAST_WARNING,
      TOAST_INFO: TOAST_INFO,
      BGC_TOAST_INFO: BGC_TOAST_INFO,
    },
  };

  const themeLight = {
    colors: {
      ...MD3LightTheme.colors,
      WHITE_COLOR: WHITE_COLOR,
      WHITE_COLOR_GRAY_100: WHITE_COLOR_GRAY_100,
      BLACK_COLOR: BLACK_COLOR,
      MAIN_COLOR: MAIN_COLOR,
      PRIMARY_COLOR: PRIMARY_COLOR,
      MAIN_TEXT_COLOR: MAIN_TEXT_COLOR,
      INFO_COLOR: INFO_COLOR,
      BGC_INFO_COLOR: BGC_INFO_COLOR,
      SUCCESS_COLOR: SUCCESS_COLOR,
      BGC_SUCCESS_COLOR: BGC_SUCCESS_COLOR,
      WARNING_COLOR: WARNING_COLOR,
      BGC_WARNING_COLOR: BGC_WARNING_COLOR,
      CRITICAL_COLOR: CRITICAL_COLOR,
      BGC_CRITICAL_COLOR: BGC_CRITICAL_COLOR,
      TOAST_SUCCESS: TOAST_SUCCESS,
      BGC_TOAST_SUCCESS: BGC_TOAST_SUCCESS,
      TOAST_CRITICAL: TOAST_CRITICAL,
      BGC_TOAST_CRITICAL: BGC_TOAST_CRITICAL,
      TOAST_WARNING: TOAST_WARNING,
      BGC_TOAST_WARNING: BGC_TOAST_WARNING,
      TOAST_INFO: TOAST_INFO,
      BGC_TOAST_INFO: BGC_TOAST_INFO,
      DISABLED_COLOR: DISABLED_COLOR,
      DATE_TEXT_COLOR: '#2d4150',
      DATE_TEXT_DISABLED_COLOR: '#d9e1e8',
      BORDER_COLOR: BORDER_COLOR,
      BACKGROUND_CARD: '#ffffff',
      BACKGROUND_CARD_TOAST: '#ffffff',
      HIGHLIGHT_COLOR: '#f1c40f',
      DRAG_ITEM_BGC_COLOR: 'rgba(0, 18, 83, 0.2)',
      BORDER_KIT_COLOR: '#dfe6e9',
      BGC_CHILD_LOADING: 'rgba(0,0,0,0.3)',
      BGC_LOADING: 'rgba(0,0,0,0.3)',
      BORDER_INPUT_COLOR: 'rgba(0,0,0,0.3)',
    },
  };
  const colors =
    appearance_display?.value === 'dark' ||
    appearance_display?.value === 'dark-no-system'
      ? themeDark?.colors
      : themeLight?.colors;

  return {
    colors,
  };
};
