export const NEW_FEED_DATA = [
  {
    id: 1,
    title: 'HCMP001',
    description: 'HCM - Phòng 1',
    iconName: 'library-outline',
    createdAt: new Date(),
    // backgroundColor: '#7f8fa6',
    // backgroundIcon: '#ffffff5a',
    // colorIcon: '#fff597',
    // textColorTitle: '#fff',
    // textColorCategory: '#fff',
    // colorIconStar: '#fff',
    iconImage: require('../../../assets/images/new_feed_icon.png'),
  },
  {
    id: 2,
    title: 'HCMP002',
    description: 'HCM - Phòng 2',
    iconName: 'library-outline',
    createdAt: new Date(),
    // backgroundColor: '#3c6382',
    // backgroundIcon: '#ffffff5a',
    // colorIcon: '#fff597',
    // textColorTitle: '#fff',
    // textColorCategory: '#fff',
    // colorIconStar: '#fff',
    iconImage: require('../../../assets/images/new_feed_icon.png'),
  },
  {
    id: 3,
    title: 'HCMP003',
    description: 'HCM - Phòng 3',
    iconName: 'library-outline',
    createdAt: new Date(),
    // backgroundColor: '#4a69bd',
    // backgroundIcon: '#ffffff5a',
    // colorIcon: '#fff597',
    // textColorTitle: '#fff',
    // textColorCategory: '#fff',
    // colorIconStar: '#fff',
    iconImage: require('../../../assets/images/new_feed_icon.png'),
  },
  {
    id: 4,
    title: 'Send Message',
    description: 'Notification Test',
    iconName: 'navigate-outline',
    createdAt: new Date(),
    send_msg: true,
    // backgroundColor: '#7f8fa6',
    // backgroundIcon: '#ffffff5a',
    // colorIcon: '#fff597',
    // textColorTitle: '#fff',
    // textColorCategory: '#fff',
    // colorIconStar: '#fff',
    iconImage: require('../../../assets/images/new_feed_icon.png'),
  },
  // {
  //   id: 5,
  //   title: 'Copy AccessToken',
  //   description: 'Access Token Test',
  //   iconName: 'navigate-outline',
  //   createdAt: new Date(),
  //   access_token: true,
  //   backgroundColor: '#38ada9',
  //   backgroundIcon: '#ffffff5a',
  //   colorIcon: '#fff597',
  //   textColorTitle: '#fff',
  //   textColorCategory: '#fff',
  //   colorIconStar: '#fff',
  //   iconImage: require('../../../assets/images/new_feed_icon.png'),
  // },
  // {
  //   id: 6,
  //   title: 'Copy Token security',
  //   description: 'Token Security Test',
  //   iconName: 'navigate-outline',
  //   createdAt: new Date(),
  //   token_security: true,
  //   backgroundColor: '#ee5253',
  //   backgroundIcon: '#ffffff5a',
  //   colorIcon: '#fff597',
  //   textColorTitle: '#fff',
  //   textColorCategory: '#fff',
  //   colorIconStar: '#fff',
  //   iconImage: require('../../../assets/images/new_feed_icon.png'),
  // },
];
